# Generated by Django 5.2.4 on 2025-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('cloudinary_id', models.CharField(max_length=255)),
                ('owner', models.EmailField(max_length=255)),
                ('original_owner', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('from_user', models.EmailField(max_length=255)),
                ('to_user', models.EmailField(max_length=255)),
                ('action', models.CharField(choices=[('TRANSFER', 'TRANSFER'), ('REVOKE', 'REVOKE')], max_length=10)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
